#spring properties
spring:
  #aop:
    #auto: true
    #proxy-target-class: false
  #messages:
    #always-use-message-format: false
    #basename: messages
    #cache-duration: -1
  #mvc:
    #dispatch-trace-request: false
    #dispatch-options-request: true
  banner:
    location: classpath:/banner/banner.txt